### ISSUE TITLE
FacebookController::FetchFriendDetails not returning friends (data)

### ISSUE THREAD

**Issue by BizziRick** [fbsamples/ios-friend-smash-v2#2]
Hello,

I'm using the latest Facebook SDK 3.2.2 for iOS and trying to work through the Friend Smasher example.  I've discovered that the startForMyFriendsWithCompletionHandler is not returning any info with the "data" key, it reports 0 objects in the fetchedFriendData array.  However, when debugging, I can see that the "summary" key is returning the correct number of friends.

I've configured permissions correctly by following the tutorial https://developers.facebook.com/docs/games/mobile/ios-tutorial 

Is there something I'm missing?

Thanks,
Rick

**Comment by BizziRick** [comment]
I see, this code "startForMyFirendsWithCompletionHandler" doesn't seem supported anymore in v2.0 of the API.  /v2.0/me/friends "now" only returns the user's friends who also use the app.  This doesn't appear to be the original intention of the Friend Smasher iOS tutorial published at https://developers.facebook.com/docs/games/mobile/ios-tutorial.

It would be nice if the iOS tutorial at the link above could be updated to work with the newer API's.  There are many game scenarios where user's would like to see a list of their Facebook friends whom don't have the app.



/*!
 @method

 @abstract
 Simple method to make a graph API request for user friends (/me/friends), creates an <FBRequest>
 then uses an <FBRequestConnection> object to start the connection with Facebook. The
 request uses the active session represented by `[FBSession activeSession]`.

 See <connectionWithSession:graphPath:parameters:HTTPMethod:completionHandler:>

 @param handler          The handler block to call when the request completes with a success, error, or cancel action.
 */
+ (FBRequestConnection *)startForMyFriendsWithCompletionHandler:(FBRequestHandler)handler;

**Comment by connortreacy** [comment]
Hi Rick, sorry to hear that you got tripped up on this step of the tutorial. It's true that the first use of `startForMyFriendsWithCompletionHandler` doesn't make it clear that you probably don't have any friends who are also playing this game, so it's likely to be a 0-length array response.

Further in the tutorial (https://developers.facebook.com/docs/games/mobile/ios-tutorial#requests) we separate out the APIs for getting in-app friends (those who have already installed your game) and non-app friends (those who haven't installed your game, to whom you may want to send an invite). Hopefully that section clarifies some of the confusion you've faced.

I've modified the tutorial to clarify the confusion you're experiencing. Let me know if this is clear enough for you.

**Comment by BizziRick** [comment]
Yes, that works.

Thanks,
Rick
